apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-slash-command-notifications
  labels:
    app: app-slash-command-notifications
spec:
  schedule: "0 6 * * 1-5"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: curlimages/curl:7.85.0
            args: 
            - /bin/sh
            - -c
            - "curl -XPOST http://app-slash-command.default.svc.cluster.local/api/v1/devenv/slack/notifications"
            name: curl
            name: app-slash-command-notifications
          restartPolicy: OnFailure

---