apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-scaler-reset
  labels:
    app: app-scaler-reset
spec:
  schedule: "0 6 * * 1-5"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: curlimages/curl:7.85.0 
            args: 
            - /bin/sh
            - -c
            - "curl -XPOST http://app-scaler.default.svc.cluster.local/api/v1/schedule/reset"
            name: curl
            name: app-scaler-reset
          restartPolicy: OnFailure
---